### ISSUE TITLE
Forgot pull request

### ISSUE THREAD

**Issue by BrysonRafael** [chris-held/whosnatchedit#9]
Hey Chris,

Just forked your project, fixed a typo, and merged to master without thinking. Sorry about that : ( I'm usually the only one who uses github on my team, so I've developed a bad habit. Anyways, thanks for your blog post on react hooks, it's interesting to see how it makes a difference in a larger project.

**Comment by chris-held** [comment]
Haha, no worries. Glad you liked the post!
